### ISSUE TITLE
Can't build library with gcc and clang for knl

### ISSUE THREAD

**Issue by marehr** [edanor/umesimd#1]
Hi umesimd developers, 

first of all, thank you for your great work and effort.
And it is also great to see that you migrated to github.

Now to my issue, in `umesimd/examples/`

> g++-6 -std=c++11  -march=knl Example1.cpp

and 

>  clang++-3.9 -std=c++11 -march=knl Example1.cpp

will result in similar errors of missing functions:

```
In file included from Example1.cpp:31:
In file included from ./../UMESimd.h:133:
In file included from ./../plugins/UMESimdPluginAVX512.h:98:
In file included from ./../plugins/avx512/UMESimdVecUintAVX512.h:52:
./../plugins/avx512/uint/UMESimdVecUint32_4.h:977:31: error: use of undeclared identifier '_mm512_reduce_add_epi32'
            uint32_t retval = _mm512_reduce_add_epi32(t0);
                              ^
./../plugins/avx512/uint/UMESimdVecUint32_4.h:984:31: error: use of undeclared identifier '_mm512_mask_reduce_add_epi32'
            uint32_t retval = _mm512_mask_reduce_add_epi32(t1, t0);
                              ^
./../plugins/avx512/uint/UMESimdVecUint32_4.h:990:31: error: use of undeclared identifier '_mm512_reduce_add_epi32'
            uint32_t retval = _mm512_reduce_add_epi32(t0);
                              ^
[...]
```

Because we are also an IPCC, we asked our persons in charge and they said, that it seems that not all intrinsics are integral part of the architecture’s instruction set but extensions in software (like the reduce intrinsics). Since it seems that gcc  and a clang add those feature way later, it would be nice to be able to compile the library regardless of the compiler.

**Comment by edanor** [comment]
Seems like GCC is still missing most of the horizontal reductions, and this was not caught due to unit tests not building correctly when GCC/CLANG was used on AVX512 machines. 

For CLANG two more issues:
- _mm512_castsi128_si512 was missing in pre-3.9 releases. Because it is available in the most recent compiler release, no workaround is introduced. Instead I will increase the compatible compiler version for UME::SIMD
- missing definitions for _MM_CMPINT... macros. I've added a workaround for up to 3.9, but it seems that this should be fixed already in 4.0.

Also added tests for horizontal addition/multiplication, but I guess they might need some more elaborate form (e.g. multiplying 16 FP elements can easily cause overflow). But at least build can be tested with those.

You should be now able to build with g++ (5.3+) and clang++(3.9.0).

Because this change was pretty extensive, I suggest closing this topic and reporting on each problem that might still be present individually.

**Comment by marehr** [comment]
Thank you for your effort, it compiles now with both compilers :+1: 

But, compiling on clang 3.9 with `-march=knl` will produce an image, that segfaults in `sde`.

```
> ./sde-external-7.49.0-2016-07-07-lin/sde64 -ptr-check -knl -- ./bin/test_basic_simd_vector
Illegal instruction at address = 59e6a5: 82 e0 01 88 c1 c5 f8 92 c1 c5 f8 91 85 76 ff 
Image name: ~/clang/bin/test_basic_simd_vector
Offset in image: 0x19e6a5
If you believe your application should attempt to execute
this illegal instruction (and others that may be present),
Then use this knob: -emit-illegal-insts 0
and this error message will be avoided.
```

I'll try to figure out what goes wrong.

**Comment by edanor** [comment]
I've seen that with unit tests, and it fails when compiling scalar code.

**Comment by edanor** [comment]
Confirmed - this is a compiler issue. The minimal test showing the same problem looks like this:
```
#include <random>
#include <iostream>

bool fun(std::mt19937 & generator) {
    std::uniform_int_distribution<int32_t> dist(std::numeric_limits<int32_t>::min(), std::numeric_limits<int32_t>::max());
    int32_t t0 = dist(generator);
    return t0 > 0;
}

int main()
{
    std::random_device rd;
    std::mt19937 gen(rd());

    bool x;
    x = fun(gen);

    std::cout << x;
    return 0;
}
```

I've sent a notification about this issue to LLVM admins. 
I think this issue might be somehow related to: https://llvm.org/bugs/show_bug.cgi?id=30502

**Comment by marehr** [comment]
Nice, thank you!

**Comment by marehr** [comment]
Hi me, again.

The following won't work for clang:

`clang++-3.9 -std=c++11 -mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl -mavx512ifma -mavx512vbmi Example1.cpp`

```
In file included from Example1.cpp:31:
In file included from ./../UMESimd.h:133:
In file included from ./../plugins/UMESimdPluginAVX512.h:109:
In file included from ./../plugins/avx512/UMESimdVecFloatAVX512.h:61:
./../plugins/avx512/float/UMESimdVecFloat64_4.h:1216:26: error: always_inline function '_mm256_fmadd_pd' requires target feature 'fma', but would be
      inlined into function 'fmuladd' that is compiled without support for 'fma'
            __m256d t0 = _mm256_fmadd_pd(mVec, b.mVec, c.mVec);
                         ^
```

And g++-6.2 seems to not support the masking functions of `_mm_*` and `_mm256_*`, `_mm512_*` versions seem to work.

`g++-6 -std=c++11 -mavx512f -mavx512cd -mavx512bw -mavx512dq -mavx512vl -mavx512ifma -mavx512vbmi Example1.cpp`

```
In file included from ../plugins/avx512/UMESimdVecUintAVX512.h:55:0,
                 from ../plugins/UMESimdPluginAVX512.h:107,
                 from ../UMESimd.h:133,
                 from Example1.cpp:31:
../plugins/avx512/uint/UMESimdVecUint32_4.h: In member function ‘UME::SIMD::SIMDVecMask<4u> UME::SIMD::SIMDVec_u<unsigned int, 4u>::cmpne(const UME::SIMD::SIMDVec_u<unsigned int, 4u>&) const’:
../plugins/avx512/uint/UMESimdVecUint32_4.h:759:61: error: ‘_mm_cmpneq_epu32_mask’ was not declared in this scope
             __mmask8 m0 = _mm_cmpneq_epu32_mask(mVec, b.mVec);
                                                             ^
../plugins/avx512/uint/UMESimdVecUint32_4.h: In member function ‘UME::SIMD::SIMDVecMask<4u> UME::SIMD::SIMDVec_u<unsigned int, 4u>::cmpne(uint32_t) const’:
../plugins/avx512/uint/UMESimdVecUint32_4.h:777:57: error: ‘_mm_cmpneq_epu32_mask’ was not declared in this scope
             __mmask8 m0 = _mm_cmpneq_epu32_mask(mVec, t0);
                                                         ^
[...]

In file included from ../plugins/avx512/UMESimdVecUintAVX512.h:56:0,
                 from ../plugins/UMESimdPluginAVX512.h:107,
                 from ../UMESimd.h:133,
                 from Example1.cpp:31:
../plugins/avx512/uint/UMESimdVecUint32_8.h: In member function ‘UME::SIMD::SIMDVecMask<8u> UME::SIMD::SIMDVec_u<unsigned int, 8u>::cmpne(const UME::SIMD::SIMDVec_u<unsigned int, 8u>&) const’:
../plugins/avx512/uint/UMESimdVecUint32_8.h:776:64: error: ‘_mm256_cmpneq_epu32_mask’ was not declared in this scope
             __mmask8 m0 = _mm256_cmpneq_epu32_mask(mVec, b.mVec);
                                                                ^
```

**Comment by edanor** [comment]
Marcel,

for the Clang problem the solution seems straightforward: compile time safeguards for the FMA instructions.

The problems that you see with GCC are related to AVX512-VL and AVX512-DQ extensions. GCC version 6.2 does not expose proper intrinsics at this moment. I don't want to do a permanent workaround for GCC, as then performance might be hurt when a compatible version is available. I will only do a workaround on version up to 6.2. If the support is still not there in 6.3, I will just up the workaround version.

**Comment by edanor** [comment]
Ready for verification.

**Comment by marehr** [comment]
Nice, it works!
